### ISSUE TITLE
Fedora permission denied.

### ISSUE THREAD

**Issue by the-twee** [readingschool-cs-club/pychat#1]
Tried running server.py with following commands but didn't work:

[Shreyas@codezone Github]$ git clone "https://github.com/readingschool-cs-club/pychat.git"
Cloning into 'pychat'...
remote: Counting objects: 3721, done.
remote: Compressing objects: 100% (1271/1271), done.
remote: Total 3721 (delta 2460), reused 3699 (delta 2449), pack-reused 0
Receiving objects: 100% (3721/3721), 284.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2460/2460), done.
Checking connectivity... done.
[Shreyas@codezone Github]$ ls
JayI pychat
[Shreyas@codezone Github]$ cd pychat
[Shreyas@codezone pychat]$ ./server.py
bash: ./server.py: Permission denied
[Shreyas@codezone pychat]$ sudo -s
[sudo] password for Shreyas:
[root@codezone pychat]$ ./server.py
bash: ./server.py: Permission denied

**Comment by the-twee** [comment]
even doing python server.py doesn't work

**Comment by saleemrashid1** [comment]
`./server.py` works

**Comment by saleemrashid1** [comment]
And learn how Linux works!

**Comment by the-twee** [comment]
I got it working with python server.py and python client.py 
and I've learnt everything you said I had to learn now don't keep telling me to learn anything else even after i've learnt what you asked me

**Comment by saleemrashid1** [comment]
Check your github page

**Comment by saleemrashid1** [comment]
Anyway, I mean learn how things work as you go!

You know the basics, you can find the rest out.

**Comment by the-twee** [comment]
why the hell did u write that even after i told u

**Comment by the-twee** [comment]
clear it mess up ur own page

**Comment by the-twee** [comment]
GET RID OF IT

**Comment by saleemrashid1** [comment]
why? it is cool!

**Comment by the-twee** [comment]
I SAID GET RID OF DO ANYTHING U WANT TO DO TO UR OWN PROFILE NOT MINE

**Comment by saleemrashid1** [comment]
calm. down.

**Comment by saleemrashid1** [comment]
just need to do some cleaning up of my own Fedora system
