### ISSUE TITLE
WHY DID YOU JUST POST MY EMAIL

### ISSUE THREAD

**Issue by the-twee** [readingschool-cs-club/pychat#6]

**Comment by saleemrashid1** [comment]
WHAT? I DOING IT FROM COMMAND LINE USING HUB

**Comment by saleemrashid1** [comment]
YOUR EMAIL IS PUBLIC!

OPEN A GIT REPO AND TYPE `git log`

EVERYONE CAN SEE

**Comment by saleemrashid1** [comment]
I WILL REPORT YOU JUST GET OFF MY CASE

**Comment by saleemrashid1** [comment]
GO INTO JAYI AND TYPE `git log`
